# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "q6hY^GTLyF@jWfOJgQ&B"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "9A#SjKVcn!Gh#C8BPLsa"
    salt: "2#BCiMGr9alH%IRBAPj1"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  naturemed.org:
    env:
      db_password: "yQiQ3!h5csQfgfHu$YDa"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "$94/c?gy4mBx/`k3MMoQ[i0Uce#Vh:A@!)WGY!J{:)Mu[nA-co=2i%E)Fg$OshaF"
      secure_auth_key: "*HYAt_O3c}#N>zE_1^mOlT9NVJ.I(-MgbO/%N#%_*;Nb<?R/vtVaxCf%Re`46w>["
      logged_in_key: "Do|w%w)Y}4Sn?K4cY7/j2`Q<IlaP=`avxAzh#(6cD3*dncQQufC.I[V<EU@NuA{K"
      nonce_key: "BRkXlrXwn!h+GH?9Ze-%#.U[d)&NXAdCFE8C)NQ/T[9%n=<beZYb196LanY:8=6&"
      auth_salt: "2S5zZ!9j/m8yPE-{],Wc65F@NQLiB^*V$0smV^7Ha3Mj?$S;iZ.BQ:<N4j`^!(zu"
      secure_auth_salt: "=*HgSAuJ66rY05%AijwX}bjP-Fv_$5q`xqjXGnv5B$JtNi>NT{NtS1hayd&NKX^+"
      logged_in_salt: "t4Cd*jLwx:V4cru/auE-RuqtPaGQC4bl=CN`vN4oRb0*-@qS,L?7Ldht.hWyej*?"
      nonce_salt: "w,-U161[g5GM(2d(esI-+?oJ5sfB]FBkVgl,0B3+%@:3n7LzpQhwti?OieFyg?<<"
